name: Create Package Version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://salesforce/salesforcedx:latest-full
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify and create package version
        run: |
          echo ${{ secrets.DEV_HUB_URL }} > devHubURLFile
          sfdx force:auth:sfdxurl:store -d -f devHubURLFile
          rm devHubURLFile

          chmod +x ./scripts/createPackage.sh
          ./scripts/createPackage.sh -p